[workspace]
resolver = "2"
members = [
    "black-hole-beam",
    "black-hole-flux",
    "black-hole-quark",
    "black-hole-sun",
    "black-hole-test",
    "black-hole-type",
]

[workspace.dependencies]
jungle-sdk = { git = "https://github.com/nicksenger/Jungle.git", branch = "master" }
jungle-vision = { git = "https://github.com/nicksenger/Jungle.git", branch = "master" }
jungle-zoo = { git = "https://github.com/nicksenger/Jungle.git", branch = "master" }

[workspace.lints.clippy]
type_complexity = "allow"
