[workspace]
resolver = "2"
members = [
    "_black_hole_beam",
    "_black_hole_flux",
    "_black_hole_quark",
    "_black_hole_void",
    "black-hole-sun",
    "_black_hole_probe",
    "_black_hole_spec",
]

[workspace.dependencies]
jungle-sdk = { git = "https://github.com/nicksenger/Jungle.git", branch = "blackholesun" }
jungle-vision = { git = "https://github.com/nicksenger/Jungle.git", branch = "blackholesun" }
jungle-zoo = { git = "https://github.com/nicksenger/Jungle.git", branch = "blackholesun" }

[workspace.lints.clippy]
type_complexity = "allow"
