[package]
name = "black-hole-spec"
description = "Interface types for black-hole-sun"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }

[dev-dependencies]
postcard = { version = "1", features = ["alloc"] }

[lints]
workspace = true
