[package]
name = "black-hole-flux"
description = "Jungle flow for black-hole-sun"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
black-hole-spec = { path = "../_black_hole_spec" }
black-hole-type = { path = "../_black_hole_type" }
futures = "0.3"
jungle-sdk = { workspace = true }
jungle-zoo = { workspace = true }
typosaurus = { workspace = true }
typenum = "1"
postcard = "1"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }

[lints]
workspace = true

[dev-dependencies]
trybuild = "1"
